/**
 * ISO 3166-1 alpha-2 countries.
 *
 * One list for the API, both consoles and the app. Nationality is stored as the
 * code and rendered as the name, so this is the only place a spelling lives.
 * `gender` set the opposite precedent — a free string whose valid values were
 * duplicated across three hardcoded UI lists — and at ~250 countries that would
 * have been considerably worse.
 *
 * Aliases exist because people search for the name they use rather than the one
 * a standards body prints: someone in Dubai types "UAE", and anyone with a
 * plain keyboard types "Turkiye" without the diacritic.
 */

export interface Country {
  code: string;
  name: string;
  /** Extra lower-case terms a search box should also match. */
  aliases?: string;
}

const ROWS: Array<[string, string, string?]> = [
  ['AF', "Afghanistan"],
  ['AX', "Åland Islands", 'aland'],
  ['AL', "Albania"],
  ['DZ', "Algeria"],
  ['AS', "American Samoa"],
  ['AD', "Andorra"],
  ['AO', "Angola"],
  ['AI', "Anguilla"],
  ['AQ', "Antarctica"],
  ['AG', "Antigua and Barbuda"],
  ['AR', "Argentina"],
  ['AM', "Armenia"],
  ['AW', "Aruba"],
  ['AU', "Australia"],
  ['AT', "Austria"],
  ['AZ', "Azerbaijan"],
  ['BS', "Bahamas"],
  ['BH', "Bahrain"],
  ['BD', "Bangladesh"],
  ['BB', "Barbados"],
  ['BY', "Belarus"],
  ['BE', "Belgium"],
  ['BZ', "Belize"],
  ['BJ', "Benin"],
  ['BM', "Bermuda"],
  ['BT', "Bhutan"],
  ['BO', "Bolivia"],
  ['BQ', "Bonaire, Sint Eustatius and Saba"],
  ['BA', "Bosnia and Herzegovina"],
  ['BW', "Botswana"],
  ['BV', "Bouvet Island"],
  ['BR', "Brazil"],
  ['IO', "British Indian Ocean Territory"],
  ['BN', "Brunei"],
  ['BG', "Bulgaria"],
  ['BF', "Burkina Faso"],
  ['BI', "Burundi"],
  ['CV', "Cabo Verde", 'cape verde'],
  ['KH', "Cambodia"],
  ['CM', "Cameroon"],
  ['CA', "Canada"],
  ['KY', "Cayman Islands"],
  ['CF', "Central African Republic"],
  ['TD', "Chad"],
  ['CL', "Chile"],
  ['CN', "China"],
  ['CX', "Christmas Island"],
  ['CC', "Cocos (Keeling) Islands"],
  ['CO', "Colombia"],
  ['KM', "Comoros"],
  ['CG', "Congo"],
  ['CD', "Congo (Democratic Republic)", 'drc zaire'],
  ['CK', "Cook Islands"],
  ['CR', "Costa Rica"],
  ['CI', "Côte d’Ivoire", 'cote divoire ivory coast'],
  ['HR', "Croatia"],
  ['CU', "Cuba"],
  ['CW', "Curaçao", 'curacao'],
  ['CY', "Cyprus"],
  ['CZ', "Czechia", 'czech republic'],
  ['DK', "Denmark"],
  ['DJ', "Djibouti"],
  ['DM', "Dominica"],
  ['DO', "Dominican Republic"],
  ['EC', "Ecuador"],
  ['EG', "Egypt"],
  ['SV', "El Salvador"],
  ['GQ', "Equatorial Guinea"],
  ['ER', "Eritrea"],
  ['EE', "Estonia"],
  ['SZ', "Eswatini", 'swaziland'],
  ['ET', "Ethiopia"],
  ['FK', "Falkland Islands"],
  ['FO', "Faroe Islands"],
  ['FJ', "Fiji"],
  ['FI', "Finland"],
  ['FR', "France"],
  ['GF', "French Guiana"],
  ['PF', "French Polynesia"],
  ['TF', "French Southern Territories"],
  ['GA', "Gabon"],
  ['GM', "Gambia"],
  ['GE', "Georgia"],
  ['DE', "Germany"],
  ['GH', "Ghana"],
  ['GI', "Gibraltar"],
  ['GR', "Greece"],
  ['GL', "Greenland"],
  ['GD', "Grenada"],
  ['GP', "Guadeloupe"],
  ['GU', "Guam"],
  ['GT', "Guatemala"],
  ['GG', "Guernsey"],
  ['GN', "Guinea"],
  ['GW', "Guinea-Bissau"],
  ['GY', "Guyana"],
  ['HT', "Haiti"],
  ['HM', "Heard Island and McDonald Islands"],
  ['VA', "Holy See", 'vatican'],
  ['HN', "Honduras"],
  ['HK', "Hong Kong"],
  ['HU', "Hungary"],
  ['IS', "Iceland"],
  ['IN', "India"],
  ['ID', "Indonesia"],
  ['IR', "Iran"],
  ['IQ', "Iraq"],
  ['IE', "Ireland"],
  ['IM', "Isle of Man"],
  ['IL', "Israel"],
  ['IT', "Italy"],
  ['JM', "Jamaica"],
  ['JP', "Japan"],
  ['JE', "Jersey"],
  ['JO', "Jordan"],
  ['KZ', "Kazakhstan"],
  ['KE', "Kenya"],
  ['KI', "Kiribati"],
  ['KP', "Korea (North)", 'north korea dprk'],
  ['KR', "Korea (South)", 'south korea'],
  ['KW', "Kuwait"],
  ['KG', "Kyrgyzstan"],
  ['LA', "Laos"],
  ['LV', "Latvia"],
  ['LB', "Lebanon"],
  ['LS', "Lesotho"],
  ['LR', "Liberia"],
  ['LY', "Libya"],
  ['LI', "Liechtenstein"],
  ['LT', "Lithuania"],
  ['LU', "Luxembourg"],
  ['MO', "Macao"],
  ['MG', "Madagascar"],
  ['MW', "Malawi"],
  ['MY', "Malaysia"],
  ['MV', "Maldives"],
  ['ML', "Mali"],
  ['MT', "Malta"],
  ['MH', "Marshall Islands"],
  ['MQ', "Martinique"],
  ['MR', "Mauritania"],
  ['MU', "Mauritius"],
  ['YT', "Mayotte"],
  ['MX', "Mexico"],
  ['FM', "Micronesia"],
  ['MD', "Moldova"],
  ['MC', "Monaco"],
  ['MN', "Mongolia"],
  ['ME', "Montenegro"],
  ['MS', "Montserrat"],
  ['MA', "Morocco"],
  ['MZ', "Mozambique"],
  ['MM', "Myanmar", 'burma'],
  ['NA', "Namibia"],
  ['NR', "Nauru"],
  ['NP', "Nepal"],
  ['NL', "Netherlands", 'holland dutch'],
  ['NC', "New Caledonia"],
  ['NZ', "New Zealand"],
  ['NI', "Nicaragua"],
  ['NE', "Niger"],
  ['NG', "Nigeria"],
  ['NU', "Niue"],
  ['NF', "Norfolk Island"],
  ['MK', "North Macedonia", 'macedonia'],
  ['MP', "Northern Mariana Islands"],
  ['NO', "Norway"],
  ['OM', "Oman"],
  ['PK', "Pakistan"],
  ['PW', "Palau"],
  ['PS', "Palestine"],
  ['PA', "Panama"],
  ['PG', "Papua New Guinea"],
  ['PY', "Paraguay"],
  ['PE', "Peru"],
  ['PH', "Philippines"],
  ['PN', "Pitcairn Islands"],
  ['PL', "Poland"],
  ['PT', "Portugal"],
  ['PR', "Puerto Rico"],
  ['QA', "Qatar"],
  ['RE', "Réunion", 'reunion'],
  ['RO', "Romania"],
  ['RU', "Russia"],
  ['RW', "Rwanda"],
  ['BL', "Saint Barthélemy", 'saint barthelemy'],
  ['SH', "Saint Helena, Ascension and Tristan da Cunha"],
  ['KN', "Saint Kitts and Nevis"],
  ['LC', "Saint Lucia"],
  ['MF', "Saint Martin (French part)"],
  ['PM', "Saint Pierre and Miquelon"],
  ['VC', "Saint Vincent and the Grenadines"],
  ['WS', "Samoa"],
  ['SM', "San Marino"],
  ['ST', "Sao Tome and Principe"],
  ['SA', "Saudi Arabia", 'ksa'],
  ['SN', "Senegal"],
  ['RS', "Serbia"],
  ['SC', "Seychelles"],
  ['SL', "Sierra Leone"],
  ['SG', "Singapore"],
  ['SX', "Sint Maarten (Dutch part)"],
  ['SK', "Slovakia"],
  ['SI', "Slovenia"],
  ['SB', "Solomon Islands"],
  ['SO', "Somalia"],
  ['ZA', "South Africa"],
  ['GS', "South Georgia and the South Sandwich Islands"],
  ['SS', "South Sudan"],
  ['ES', "Spain"],
  ['LK', "Sri Lanka"],
  ['SD', "Sudan"],
  ['SR', "Suriname"],
  ['SJ', "Svalbard and Jan Mayen"],
  ['SE', "Sweden"],
  ['CH', "Switzerland"],
  ['SY', "Syria"],
  ['TW', "Taiwan"],
  ['TJ', "Tajikistan"],
  ['TZ', "Tanzania"],
  ['TH', "Thailand"],
  ['TL', "Timor-Leste", 'east timor'],
  ['TG', "Togo"],
  ['TK', "Tokelau"],
  ['TO', "Tonga"],
  ['TT', "Trinidad and Tobago"],
  ['TN', "Tunisia"],
  ['TR', "Türkiye", 'turkiye turkey'],
  ['TM', "Turkmenistan"],
  ['TC', "Turks and Caicos Islands"],
  ['TV', "Tuvalu"],
  ['UG', "Uganda"],
  ['UA', "Ukraine"],
  ['AE', "United Arab Emirates", 'uae emirates dubai abu dhabi'],
  ['GB', "United Kingdom", 'uk britain england scotland wales northern ireland'],
  ['US', "United States", 'usa america'],
  ['UM', "United States Minor Outlying Islands"],
  ['UY', "Uruguay"],
  ['UZ', "Uzbekistan"],
  ['VU', "Vanuatu"],
  ['VE', "Venezuela"],
  ['VN', "Vietnam"],
  ['VG', "Virgin Islands (British)"],
  ['VI', "Virgin Islands (U.S.)"],
  ['WF', "Wallis and Futuna"],
  ['EH', "Western Sahara"],
  ['YE', "Yemen"],
  ['ZM', "Zambia"],
  ['ZW', "Zimbabwe"],
];

export const COUNTRIES: Country[] = ROWS.map(([code, name, aliases]) => ({ code, name, aliases }));

const BY_CODE = new Map(COUNTRIES.map((c) => [c.code, c]));

/** True for a well-formed, known alpha-2 code. Case-insensitive. */
export function isCountryCode(v: unknown): boolean {
  return typeof v === 'string' && BY_CODE.has(v.trim().toUpperCase());
}

/** The country's English name, or the code back if it isn't one we know. */
export function countryName(code: string | null | undefined): string {
  if (!code) return '';
  return BY_CODE.get(code.trim().toUpperCase())?.name ?? code;
}

/** Months, for birthday targeting. */
export const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];
